/**
 * SummaryView — the AI-generated meeting summary (PRD-5).
 *
 * Loads `<id>/summary.json` via `window.loqui.postprocess.getSummary`
 * (READ-ONLY) and renders the four structured sections: TL;DR, key decisions,
 * action items (with an owner when one was inferred), and topics. A "Regenerate"
 * button fires `regenerateSummary` (a summary-only re-run); progress arrives on
 * the shared {@link useJobProgress} `onJob` stream, so the parent passes a
 * `regenerating` flag + bumps `reloadKey` when the summary job completes to
 * trigger a refetch.
 *
 * CROSS-CUTTING INVARIANT: the summary is AI-generated but is a SEPARATE derived
 * file — the provider stays READ-ONLY over the transcript. This view only reads
 * the summary + asks main to regenerate it; it never writes the transcript.
 *
 * Talks ONLY to the typed `window.loqui.postprocess` bridge (injectable for
 * tests), never to IPC channels or Node globals.
 */
import { useCallback, useEffect, useState, type JSX } from "react";
import type { Summary } from "@loqui/shared";
import type { LoquiPostProcessApi } from "../../preload/index.js";
import { summaryHasContent } from "../summary/index.js";
import "../summary/summary.css";

export interface SummaryViewProps {
  /** The meeting whose summary to load. */
  meetingId: string;
  /** Postprocess bridge (subset). Injectable for tests; defaults to window.loqui.postprocess. */
  api?: Pick<LoquiPostProcessApi, "getSummary" | "regenerateSummary">;
  /**
   * Bumped by the parent (e.g. on a summary "done" JobEvent) to refetch the
   * regenerated summary. Optional.
   */
  reloadKey?: number;
  /** Whether a regenerate is currently in flight (drives the button label). */
  regenerating?: boolean;
  /** Fired when the user clicks Regenerate (after the bridge call is sent). */
  onRegenerate?: () => void;
}

type LoadState =
  | { kind: "loading" }
  | { kind: "absent" }
  | { kind: "loaded"; summary: Summary }
  | { kind: "error"; message: string };

export function SummaryView({
  meetingId,
  api,
  reloadKey,
  regenerating = false,
  onRegenerate,
}: SummaryViewProps): JSX.Element {
  const bridge =
    api ?? (typeof window !== "undefined" ? window.loqui?.postprocess : undefined);
  const [load, setLoad] = useState<LoadState>({ kind: "loading" });

  useEffect(() => {
    let cancelled = false;
    setLoad({ kind: "loading" });
    if (!bridge?.getSummary) {
      setLoad({ kind: "absent" });
      return;
    }
    bridge
      .getSummary({ meetingId })
      .then((summary) => {
        if (cancelled) return;
        setLoad(summary ? { kind: "loaded", summary } : { kind: "absent" });
      })
      .catch((err: unknown) => {
        if (!cancelled) {
          setLoad({ kind: "error", message: err instanceof Error ? err.message : String(err) });
        }
      });
    return () => {
      cancelled = true;
    };
  }, [bridge, meetingId, reloadKey]);

  const onRegenerateClick = useCallback(() => {
    if (!bridge?.regenerateSummary) return;
    void bridge.regenerateSummary({ meetingId });
    onRegenerate?.();
  }, [bridge, meetingId, onRegenerate]);

  const summary = load.kind === "loaded" ? load.summary : null;
  const canRegenerate = Boolean(bridge?.regenerateSummary);

  return (
    <section className="summary" data-testid="summary-view" aria-labelledby="summary-title">
      <div className="summary__bar">
        <div>
          <h3 className="summary__title" id="summary-title">
            Summary
          </h3>
          {summary && (summary.provider || summary.model) && (
            <p className="summary__by" data-testid="summary-provider">
              Generated by {summary.provider}
              {summary.model ? ` · ${summary.model}` : ""}
            </p>
          )}
        </div>
        {canRegenerate && (
          <button
            type="button"
            className="summary__regenerate"
            data-testid="summary-regenerate"
            disabled={regenerating}
            onClick={onRegenerateClick}
          >
            {regenerating ? "Regenerating…" : "Regenerate"}
          </button>
        )}
      </div>

      {load.kind === "loading" && (
        <p className="summary__hint" data-testid="summary-loading">
          Loading summary…
        </p>
      )}

      {load.kind === "error" && (
        <p className="summary__error" data-testid="summary-error" role="alert">
          Could not load the summary: {load.message}
        </p>
      )}

      {load.kind === "absent" && (
        <p className="summary__hint" data-testid="summary-absent">
          No summary yet. It is generated after the meeting is processed.
        </p>
      )}

      {summary && !summaryHasContent(summary) && (
        <p className="summary__hint" data-testid="summary-empty">
          The summary is empty.
        </p>
      )}

      {summary && summaryHasContent(summary) && (
        <div className="summary__body">
          {summary.tldr.trim().length > 0 && (
            <div className="summary__section" data-testid="summary-tldr">
              <h4 className="summary__section-title">TL;DR</h4>
              <p className="summary__tldr-text">{summary.tldr}</p>
            </div>
          )}

          {summary.decisions.some((d) => d.trim().length > 0) && (
            <div className="summary__section" data-testid="summary-decisions">
              <h4 className="summary__section-title">Decisions</h4>
              <ul className="summary__list">
                {summary.decisions.map((d, i) => (
                  <li key={i} data-testid="summary-decision">
                    {d}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {summary.actionItems.some((a) => a.text.trim().length > 0) && (
            <div className="summary__section" data-testid="summary-action-items">
              <h4 className="summary__section-title">Action items</h4>
              <ul className="summary__list summary__list--actions">
                {summary.actionItems.map((a, i) => (
                  <li key={i} data-testid="summary-action-item">
                    <span className="summary__action-text">{a.text}</span>
                    {a.owner && a.owner.trim().length > 0 && (
                      <span className="summary__action-owner" data-testid="summary-action-owner">
                        {"— "}
                        {a.owner}
                      </span>
                    )}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {summary.topics.some((t) => t.trim().length > 0) && (
            <div className="summary__section" data-testid="summary-topics">
              <h4 className="summary__section-title">Topics</h4>
              <ul className="summary__chips">
                {summary.topics.map((t, i) => (
                  <li key={i} className="summary__chip" data-testid="summary-topic">
                    {t}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </section>
  );
}
